videomark/videomark

- packages/sodium/src/js/modules/AmazonPrimeVideoTypeHandler.js
from: https://github.com/videomark/sodium.js/pull/42
> amazonの画質自動制御

- packages/sodium/src/js/modules/ParaviTypeHandler.js
from: https://github.com/videomark/sodium.js/pull/41
> paraviの画質自動制御

- packages/sodium/src/js/modules/NicoLiveTypeHandler.js
- packages/sodium/src/js/modules/NicoVideoTypeHandler.js
- packages/sodium/src/js/modules/VideoData.js
- packages/sodium/src/js/modules/VideoHandler.js
- packages/sodium/src/js/modules/YouTubeTypeHandler.js
from: https://github.com/videomark/sodium.js/pull/45
> スループットの自動制御の有無を送信

- .github/workflows/e2e.yml
- package.json
- test/e2e/setup.js
- test/e2e/teardown.js
- それに伴い最新の拡張機能のダウンロード機能を削除
- ビルド結果が削除される問題の修正
> テスト実行時にビルドするようにプロセスの変更

- packages/videomark-log-view/src/js/containers/Stats.jsx
Fix https://github.com/webdino/sodium/issues/482
> 計測結果画面の QoE グラフで凡例がオーバーフローする問題を修正

- packages/videomark-log-view/src/Popup.jsx
- packages/videomark-log-view/src/js/containers/History/index.jsx
Fix https://github.com/webdino/sodium/issues/632
> UI 上の用語不一致 : 計測結果 / 測定結果

- packages/videomark-log-view/src/Popup.jsx
Fix https://github.com/webdino/sodium/issues/635
#50 で発生したリグレッションのようです。
> 拡張機能のツールバーメニュー選択でタブが 2 つ開かれる問題を修正

- packages/videomark-extension/manifest.json
「拡張機能」という用語を使うように修正しました。
- 拡張機能説明文表現の修正/用語の統一
- bump minor version
> 拡張機能説明文表現の修正/用語の統一/bump version

- packages/sodium/src/js/modules/SessionData.js
ビットレートコントロール関連の他の設定がオフで無効値 undefined を得るケースがあるのでその対処
確認したこと:
- 「ネットワークの混雑する時間帯にはビットレートを制限する」有効かつビットレートコントロール関連の他の設定がオフのケースで bitrateControlData に意図した値が含まれること
> fix: ビットレート制限有効時意図した値が送信されない問題の修正

- packages/videomark-log-view/src/css/MeasureContents.module.css
- packages/videomark-log-view/src/js/components/QoEValueGraphList.jsx
- packages/videomark-log-view/src/js/components/RegionalAverageQoEGraph.jsx
- packages/videomark-log-view/src/js/containers/History/MonthSelect.jsx
- packages/videomark-log-view/src/js/containers/Viewing.jsx
Fix https://github.com/webdino/sodium/issues/646
> 履歴ページのサムネイル上に QoE 値と再生ボタンを表示

- packages/sodium/src/js/modules/GeneralTypeHandler.js
- packages/sodium/src/js/modules/ParaviTypeHandler.js
- packages/sodium/src/js/modules/VideoHandler.js
- packages/sodium/src/js/modules/YouTubeTypeHandler.js
HTMLMediaElement.duration は NaN, +Infinity の値となる可能性がある為、変更。
>  HTMLMediaElement の duration で得られる値の補正 #683

- packages/sodium/src/js/modules/IIJTypeHandler.js
- packages/videomark-extension/manifest.json
- fix: `IIJ_MPD_PATH` の更新
- chore: bump version (v1.8.0)
> fix: `IIJ_MPD_PATH` の更新

- packages/videomark-log-view/src/StatsSummary.jsx
- packages/videomark-log-view/src/js/components/ErrorSnackbar.jsx
- packages/videomark-log-view/src/js/components/QoEValueGraph.jsx
- packages/videomark-log-view/src/js/components/SimplePage.jsx
- packages/videomark-log-view/src/js/components/VideoQuality.jsx
- packages/videomark-log-view/src/js/containers/StatsDataProvider.jsx
- packages/videomark-log-view/src/js/containers/ViewingDetail.jsx
- packages/videomark-log-view/src/js/containers/ViewingsProvider.jsx
erase "eslint-disable-line react/jsx-props-no-spreading"
resolve #165
> erase eslint-disable-line (react)

- packages/sodium/src/js/modules/AbemaTVLiveTypeHandler.js
- packages/sodium/src/js/modules/DTVTypeHandler.js
- packages/sodium/src/js/modules/IIJTypeHandler.js
- packages/sodium/src/js/modules/NHKOndemandTypeHandler.js
- packages/sodium/src/js/modules/NicoLiveTypeHandler.js
- packages/sodium/src/js/modules/NicoVideoTypeHandler.js
- packages/sodium/src/js/modules/ParaviTypeHandler.js
- packages/sodium/src/js/modules/SessionData.js
- packages/sodium/src/js/modules/VideoData.js
- packages/sodium/src/js/modules/VideoHandler.js
> erase eslint-disable-next-line camelcase

- packages/sodium/src/js/App.js
- packages/sodium/src/js/modules/IIJTypeHandler.js
- packages/sodium/src/js/modules/ParaviTypeHandler.js
- packages/sodium/src/js/modules/SessionData.js
- packages/sodium/src/js/modules/VideoData.js
- packages/sodium/src/js/modules/VideoHandler.js
> Erase eslint disable no console

- packages/sodium/Gruntfile.js
- packages/sodium/src/js/App.js
- packages/sodium/src/js/modules/AbemaTVLiveTypeHandler.js
- packages/sodium/src/js/modules/AbemaTVVideoTypeHandler.js
- packages/sodium/src/js/modules/AmazonPrimeVideoTypeHandler.js
- packages/sodium/src/js/modules/Config.js
- packages/sodium/src/js/modules/DTVTypeHandler.js
- packages/sodium/src/js/modules/EventData.js
- packages/sodium/src/js/modules/FodTypeHandler.js
- packages/sodium/src/js/modules/GeneralTypeHandler.js
- packages/sodium/src/js/modules/NHKOndemandTypeHandler.js
- packages/sodium/src/js/modules/NicoLiveTypeHandler.js
- packages/sodium/src/js/modules/NicoVideoTypeHandler.js
- packages/sodium/src/js/modules/ParaviTypeHandler.js
- packages/sodium/src/js/modules/Quality.js
- packages/sodium/src/js/modules/ResourceTiming.js
- packages/sodium/src/js/modules/SessionData.js
- packages/sodium/src/js/modules/StatStorage.js
- packages/sodium/src/js/modules/Storage.js
- packages/sodium/src/js/modules/TVerTypeHandler.js
- packages/sodium/src/js/modules/Utils.js
- packages/sodium/src/js/modules/VideoData.js
- packages/sodium/src/js/modules/VideoHandler.js
- packages/sodium/src/js/modules/YouTubeTypeHandler.js
- packages/sodium/webpack.common.js
- packages/sodium/webpack.dev.js
packages/sodium 以下をコマンドを使ってフォーマット
```
npx prettier --no-config --write ./src/**/*.js
npx prettier --no-config --write ./src/**/**/*.js
npx prettier --no-config --write ./webpack*.js
npx prettier --no-config --write ./Gruntfile.js
```
> packages/sodium 以下をフォーマット

- packages/sodium/src/js/modules/Config.js
- packages/sodium/src/js/modules/NetflixTypeHandler.js
- packages/sodium/src/js/modules/VideoHandler.js
- packages/videomark-extension/manifest.json
- packages/videomark-log-view/src/js/utils/videoPlatforms.js
QoE 計算可能なデータを送信るように対応した。
- UI
- log-view
部分は未対応
> Netflix 対応

- packages/sodium/src/js/modules/YouTubeTypeHandler.js
> fix: YouTubeスループット取得に失敗する問題の修正

- packages/sodium/src/js/modules/YouTubeTypeHandler.js
Resource Timing APIを使用した処理への変更
> fix: ThroughputHistory 算出の DL 時間が RTT 相当になっている問題の修正

- packages/sodium/src/js/modules/Config.js
- packages/sodium/src/js/modules/VideoHandler.js
- packages/videomark-extension/background.js
- test/e2e/setup.js
https://abema.tv/live-event/8bd58471-0d8d-409f-9e62-18b1f1c899a0 などでの生中継の計測のサポート
> feat: ABEMA FIFAワールドカップ対応

- packages/sodium/src/js/modules/AbemaTVLiveEventTypeHandler.js
- packages/sodium/src/js/modules/VideoHandler.js
ABEMA FIFAワールドカップ計測できない不具合の修正
/live-event/* 用に計測スクリプトを切り分けました
Representation listを更新しました
> fix: ABEMA FIFAワールドカップ計測できない不具合の修正

- .github/workflows/release.yml
- bin/build
- netlify.toml
- packages/videomark-extension/background.html
- packages/videomark-extension/background.js
- packages/videomark-extension/content_script.js
- packages/videomark-extension/manifest-firefox.json
- packages/videomark-extension/manifest.json
- packages/videomark-extension/request_rules.json
- packages/videomark-log-view/src/QualityUiSetting.jsx
- packages/videomark-log-view/src/js/utils/ChromeExtensionWrapper/index.js
Fix https://github.com/webdino/sodium/issues/316
以前開発したブランチを Firefox に対応させました。上記 issue に書いた通りマニフェストファイルは Chrome と分ける必要があり、ビルドスクリプトにも変更を加えています。
> Extension Manifest v3 対応

- src/lib/background/background.js
リリースノートの表示については、利用規約等への変更ほどの重要性では無いと判断しました。
> メジャーバージョンアップ時の通知の無効化

- .github/workflows/release.yml
- build: update PlasmoHQ/bpp@v3
> build: update PlasmoHQ/bpp@v3

- .github/workflows/release.yml
@kou029w 夜遅くまで済みません。なんかリリースアクションがコケていますね。BPP のパラメーターを追加して再度試してみてもらえますか？ ビルドは成功してるからファイルは存在するはずなんだけどなぁ。
https://github.com/PlasmoHQ/bpp#action-input-parameters-with
> Plasmo BPP のオプションを追加

- .github/workflows/release.yml
GitHub Actionsによるリリースワークフローの改善
- リリース時のタグの自動作成
- リリース時のリリースノートの自動作成
> chore: Gitタグ/リリースノート自動作成

- src/lib/content/sodium/README.md
- src/lib/content/sodium/modules/Config.js
- src/lib/content/sodium/modules/SessionData.js
- src/lib/locales/en.js
- src/lib/locales/ja.js
- src/lib/pages/routes/settings.svelte
- src/lib/services/settings.js
resolved https://github.com/webdino/sodium/issues/899
videomark/videomark#214 にて実装した動画の最大計測単位の長さを利用者が変更できるようになります。
> feat: 最大計測単位の設定機能

- src/lib/locales/en.js
- src/lib/locales/ja.js
- src/lib/pages/history/history-item.svelte
- src/lib/pages/popup/popup-history.svelte
- src/lib/services/navigation.js
Fix https://github.com/webdino/sodium/issues/925
> 再生中の動画は「もう一度見る」ではなく「タブを表示」にする

- src/lib/content/sodium/modules/VideoHandler.js
fixes https://github.com/webdino/sodium/issues/920
> ニコニコ生放送の正規表現を修正

- src/lib/content/sodium/modules/Config.js
> AbemaTVのDOM要素を変更

- cspell.config.yaml
- public/manifest.json
- public/request_rules.json
- src/lib/content/sodium/modules/Config.js
- src/lib/content/sodium/modules/LEMINOTypeHandler.js
- src/lib/content/sodium/modules/LeminoTypeHandler.js
- src/lib/content/sodium/modules/VideoHandler.js
- src/lib/locales/en.js
- src/lib/locales/ja.js
- src/lib/services/video-platforms.js
> Lemino support

- public/manifest-firefox.json
- public/manifest.json
- public/request_rules.json
- src/lib/background/background.js
- src/lib/content/sodium/modules/VideoHandler.js
> FODの指定URLの変更

- src/lib/content/sodium/modules/Config.js
> Netflixの指定DOM要素を変更

- src/lib/content/sodium/modules/AbemaTVLiveTypeHandler.js
> AbemaTVのビデオタイトル取得方法修正

- src/lib/content/sodium/modules/AmazonPrimeVideoTypeHandler.js
> Primeビデオのビデオタイトル取得時のDOM要素を変更

- src/lib/content/content.js
- src/lib/content/sodium/modules/Config.js
- src/lib/services/runtime.js
- src/lib/services/storage.js
- src/lib/services/support.js
Fix https://github.com/webdino/sodium/issues/959
- カスタムブラウザーか拡張機能かの判別は必要なくなったので削除します。
- ストレージのテスト用モックも必要ないかと思うので削除します。
> VideoMark ブラウザー対応の削除

- .github/workflows/lint.yml
> GitHub Actions: Lint ワークフローの Stylelint を無効化

- src/lib/content/sodium/modules/NetflixTypeHandler.js
Fix https://github.com/webdino/sodium/issues/809
動画のサムネイルとタイトル、正規 URL が正しく記録されるようにします。
> Netflix 視聴履歴の問題を修正

- src/lib/services/history.js
Fix https://github.com/webdino/sodium/issues/1039
再現条件がわかりませんが、スタックトレースを見る限り #272 で追加した行が問題なので、クイックに修正します。
> v3.0.3 への更新で履歴が表示されなくなる場合がある問題を修正

- cspell.config.yaml
- src/lib/content/sodium/modules/Config.js
- src/lib/content/sodium/modules/NicoVideoTypeHandler.js
Fix #300
[動画視聴ページが大幅に更新されて](https://blog.nicovideo.jp/niconews/238193.html) まったく動かなくなっていたようなので修正しました。手元ではオーバーレイが表示されるようになっています。
> ニコニコ動画での計測不具合を修正

- public/_locales/en/messages.json
- public/_locales/ja/messages.json
- public/manifest.json
- src/lib/background/background.js
- src/lib/content/content.js
Fix https://github.com/webdino/sodium/issues/448
デスクトップ通知を使って 2 日に 1 回程度リマインダーを表示するようにします。アナリティクスが入っていないので効果測定はできませんが...
> 利用規約未同意の場合にリマインダーを表示
