packages/sodium/src/js/App.js, packages/sodium/src/js/modules/Config.js, packages/sodium/src/js/modules/UI/index.js, test/e2e/index.test.js
Androidでの計測中表示UIが大きく変更されたことに伴い、VMBrowserでは従来m.youtube.comでプレイヤー要素を監視して表示を切り替えていた特別な対応が不要となり、またメンテナンス続けるのが難しいと考えたため削除しました
念の為テストコードも加えました
よかったら確認してもらって、特にコメント無ければ問題ないと判断して勝手にマージします
=> Androidでの計測中表示UI変更に伴うm.youtube.com対応の簡略化

.github/workflows/e2e.yml, test/e2e/index.test.js
- fix: CI環境でのテスト失敗に対処する目的でYouTube固有のクラスをやめ属性セレクターを使う
- 検索結果一覧画面への遷移処理は不要なので除去
- カンマ含まれている数字のサポート
- fix: remove duprecated method
- fix: CI環境で対応する日本語フォントが存在しない問題への対処
=> E2EテストでYouTubeトップから動画ページに移動に失敗する不具合等の修正

packages/sodium/src/js/modules/Config.js, packages/sodium/src/js/modules/SessionData.js, packages/videomark-log-view/src/Settings/PersonalSessionSettingItem.jsx, packages/videomark-log-view/src/Settings/PrivacySettings.jsx, packages/videomark-log-view/src/Settings/index.jsx, packages/videomark-log-view/src/js/utils/ChromeExtensionWrapper/index.js, packages/videomark-log-view/src/js/utils/Utils.js, packages/videomark-log-view/src/js/utils/getSessionType.js, packages/videomark-log-view/src/js/utils/overwriteSessionId.js
- dev serverで設定画面にアクセスできない問題の修正
- 個人的セッション設定機能の実装/セッション種別の送信機能の実装
確認したこと:
設定 > セッションIDの部分をトリプルクリック > セッションIDの設定後セッション種別が開発用サーバーに送信されること
=> 個人的セッション設定機能の実装/セッション種別の送信機能の実装

packages/sodium/src/js/modules/SessionData.js, packages/videomark-extension/content_script.js
https://github.com/videomark/videomark/blob/d2970a0e42cc6dcd4d4ca37a9201f24daa268539/packages/sodium/src/js/modules/SessionData.js#L111-L115
ここでマージされており videomark/videomark#116 の変更に伴い追加した `type` プロパティが衝突することで上書きされた結果 `FROM_SODIUM_JS` が失われており、意図した振る舞いをしなくなっていたため修正します。
確認したこと: 初回視聴後、UUIDv4形式のセッションIDがデフォルトの期間で固定され設定画面に表示されること。また期限を0に設定すると次回視聴時に更新されること。
=> セッションのリセット処理が視聴時実施されない問題の修正

packages/sodium/src/js/modules/IIJTypeHandler.js, packages/sodium/src/js/modules/ParaviTypeHandler.js, packages/sodium/src/js/modules/SessionData.js, packages/sodium/src/js/modules/YouTubeTypeHandler.js
latest_qoe へ送信する前に session_id, video_id を確認する
動作確認では 124 行目の次に、一時的に下記を記載し、ブラウザの Developer tools で Console ログを見て行った。
this.session.id = null;
=> POST /api/latest_qoe への送信データ確認 #560

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml
[actions/setup-node](https://github.com/actions/setup-node#readmehttps://github.com/actions/setup-node#readme)でcacheを指定可能になったので対応し、いままでのactions/cacheの対応を削除します。
=> GitHub Actions actions/setup-node の cache に対応

.eslintrc.yml, packages/sodium/README.md, packages/sodium/src/js/modules/Config.js, packages/sodium/src/js/modules/VideoData.js, packages/sodium/webpack.dev.js, packages/sodium/webpack.prod.js
EVENT_DATA_MAX_SIZE で設定した値を "event_..." のデータの size の max 値となるようにする。
=> 計測データが貯まりすぎたらクライアント側で一部捨てるか送信を止める #562

.eslintrc.yml, package.json, packages/videomark-log-view/src/QualityUiSetting.jsx, packages/videomark-log-view/src/Settings/BitrateControlSettings.jsx, packages/videomark-log-view/src/Settings/DesignSettings.jsx, packages/videomark-log-view/src/js/utils/Utils.js, yarn.lock
早期 return より後のフックの呼び出しは禁止されているため順序を修正します。
関連: b25310450b5d01354b28bdc0ad453d4efde5b365, PR #130 にて早期returnに修正したほうが良いと提案したのですが改めて調べたところ下記の規約に違反しているようです。確認不足ですみませんでした… :pray: > @kyoshino 
参考文献: https://ja.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
やったこと:
- fix: ポップアップが表示されない問題の修正
- フックAPIに依存しているならば接頭辞useを付けるリファクタリング
- フックAPIの規約を守る目的でeslint-plugin-react-hooksの導入
確認したこと:
開発用のビルドを作成後、インストールを実施し、動画視聴時に拡張機能ポップアップメニューにアクセス可能であること
=> fix: ポップアップが表示されない問題の修正

packages/videomark-log-view/src/css/MeasureContents.module.css
Fix https://github.com/webdino/sodium/issues/680
=> ダークモード以外での履歴画面の配色に関する確認

test/e2e/index.test.js
毎回失敗しているが無視しており新しい問題が発生した際に見逃す可能性があるため、修正の目処が立てられるまで無効化
=> GitHub Actions の環境にてビットレートの検知の部分で失敗するためスキップ

packages/sodium/src/js/modules/SessionData.js
件の通り。
https://github.com/webdino/sodium/issues/684
=> MessagePack への変換前に JSON.parse(JSON.stringify(payload)) する #684

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, bin/build, bin/build-android
古いバージョンのOpenSSLへの依存関係が存在するため `NODE_OPTIONS=--openssl-legacy-provider` を暫定的に指定して回避
=> fix: Netlifyでビルド失敗する問題の回避

packages/sodium/src/js/modules/AbemaTVLiveTypeHandler.js, packages/sodium/src/js/modules/VideoData.js, packages/sodium/src/js/modules/VideoHandler.js
注意点
- media size は 2 時間の固定値
- 読み込み済みバッファは再生時間 + 5 秒の固定値
- framerate, bitrate は MPD を解析した値をテーブルで持っている
- position は切り替えたタイミングからの経過時間
- イベントは無視する
- segment domain は `ds-linear-abematv.akamaized.net` の固定値
- resolution は再生中の video の videoHeight, videoWidth から取得している
- CM 時にテーブルに含まれていない resolution が再生された場合 デフォルト の 高さ 480 の framerate, bitrate が使用される
- CM 時の resolution が テーブルに含まれている値なら テーブルのものを使用する
=> Abema Live 対応

packages/sodium/src/js/modules/AbemaTVLiveTypeHandler.js, packages/sodium/src/js/modules/GeneralTypeHandler.js, packages/sodium/src/js/modules/ResourceTiming.js, packages/videomark-extension/background.js
ABEMA Live 視聴時のスループットを計測できるようにします。
※ FIFA特設サイト (/live-event/*) は非対応です。
=> feat: ABEMA (Live) スループット取得対応

README.md, packages/sodium/webpack.dev.js, packages/sodium/webpack.prod.js, packages/videomark-extension/background.js, packages/videomark-extension/manifest.json, packages/videomark-extension/terms.html, packages/videomark-log-view/public/unsupported.html, packages/videomark-log-view/src/Settings/BitrateControlSettings.jsx, packages/videomark-log-view/src/js/utils/helpURL.js, packages/videomark-mini-stats/index.js, packages/videomark-mini-stats/index.tsx
`vm.webdino.org` から `videomark.webdino.org` に一括置換しました。
=> VideoMark サイト URL を更新

.editorconfig, .gitattributes
改行コードを常に LF とするよう設定ファイルを追加します。
=> Fix #170 エディタの設定ファイルの配置

bin/build, bin/build-android
Fix https://github.com/webdino/sodium/issues/741
現状 Netlify へデプロイされていない & Svelte ベースの拡張機能 v2 への移行により、このオプションはもう必要なさそうです。
=> NODE_OPTIONS=--openssl-legacy-provider を取り除く

src/lib/pages/common/platform-list.svelte, src/lib/pages/history/search-form.svelte, src/lib/services/video-platforms.js
下記の項目での deprecated フラグが真のプラットフォームを非表示にしました。
- プラットフォーム一覧
- 検索フォーム
引き続き履歴画面には表示されます。
https://github.com/videomark/videomark/pull/203
=> gorin.jp 終了対応 (v2)

public/manifest-firefox.json
`webRequestBlocking` パーミッションは Manifest v3 では使用不可。 `declarativeNetRequest` が実装されていない Firefox 向け後方互換。
see https://bugzilla.mozilla.org/1687755
Co-authored-by: Kohei Yoshino <kohei.yoshino@gmail.com>
https://github.com/videomark/videomark/pull/205
=> fix: Firefox 向け後方互換

src/lib/content/sodium/README.md, src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/SessionData.js
resolved https://github.com/webdino/sodium/issues/885
1時間 (デフォルト) 以上の連続視聴を分割して QoE 推計を適切にします。
=> 長時間の視聴を分割して計測

src/lib/content/sodium/modules/Config.js, src/lib/pages/routes/settings.svelte
セッション保持期限の設定に関わらず、毎回新しいセッションIDに変わる不具合がありました。
セッション保持期限を反映されるようにします。
- document.currentScript プロパティは ES Module に存在しないため、代わりに対応 import.meta.url を使用するように変更します。
- セッション保持期限の設定を行ったとき session オブジェクトへの反映が行われていなかったので正しく反映されるように処理を追加しました。
=> fix: セッション保持期限に関わらず新しいセッションIDに変わる問題の修正

src/lib/pages/common/platform-list.svelte, src/lib/pages/history/history-item.svelte, src/lib/pages/history/not-found.svelte, src/lib/pages/layouts/popup-layout.svelte, src/lib/pages/onboarding/no-history.svelte, src/lib/pages/popup/popup-history.svelte, src/lib/pages/popup/popup-platform-list.svelte
Fix https://github.com/webdino/sodium/issues/895
ドロップダウンメニューを元々意図していた UX になるよう改善します。
- ヘッダーとフッターを上下に固定
- ヘッダーに設定画面を開くボタンを追加
- 表示する履歴の最大件数を設定
- 検索結果ゼロの場合に表示される YouTube 検索ボタンが動作しない問題を修正
=> ツールバードロップダウンメニューの改善

src/lib/content/sodium/modules/GeneralTypeHandler.js, src/lib/content/sodium/modules/SessionData.js, src/lib/content/sodium/modules/VideoHandler.js, src/lib/content/sodium/modules/YouTubeTypeHandler.js
下記のケースでMongoDBのsodium_collection内にあるlocationと実際に再生していた動画が紐づいていることを確認
- ミニプレーヤーで再生
- ミニプレーヤーで再生中、トラックアップで次の動画を再生
- ミニプレーヤーで再生中、ミニプレーヤーモードを解除して、トラックアップで次の動画を再生
=> Youtubeミニプレーヤー時のurl取得改善 #423

src/lib/content/sodium/modules/VideoHandler.js, src/lib/content/sodium/modules/YouTubeTypeHandler.js
https://github.com/videomark/videomark/pull/223 と同様の内容をYoutube.musicでも確認
具体的には下記
MongoDBのsodium_collection内にあるlocationと実際に再生していた動画が紐づいていることを確認
- ミニプレーヤーで再生
- ミニプレーヤーで再生中、トラックアップで次の動画を再生
- ミニプレーヤーで再生中、ミニプレーヤーモードを解除して、トラックアップで次の動画を再生
=> youtube.musicのミニプレーヤー再生時も再生中URLが取得できるように変更

src/lib/pages/routes/settings.svelte
- https://github.com/webdino/sodium/issues/936
拡張機能の `/index.html?bot=true&session_id=${sessionId}#settings` にアクセスすることで、QoE問い合わせを停止する機能を提供します。
- 最新QoE値を非表示
=> 自動計測向けの初期設定

src/lib/background/background.js
Fix https://github.com/webdino/sodium/issues/953
[`runtime.onInstalled`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled) コールバック関数の引数として渡される `reason` を見て、拡張機能インストール時のみオンボーディングページを開き、拡張機能更新時のみスキーマバージョンを確認するようにします。ツールバーボタンの挙動変更 (`chrome.action.setPopup`) は直前の `initToolbarButton` 内で重複して行っているので削除します。
=> オンボーディングページが更新時に毎回開かれる問題を修正

.github/workflows/tests.yml
package-lock.json のハッシュ値が使用されていましたが、package-lock.json はこのコードベース内には存在しません。 代わりに pnpm-lock.yaml ハッシュ値を使用するように変更します
=> ci: キャッシュのキーとして pnpm-lock.yaml のハッシュ値を使用するように変更

public/manifest-firefox.json
Firefoxのmanifest.jsonのstrict\_min\_versionを更新しています。
アドオンの検証で警告が出ていたためです。
https://addons.mozilla.org/ja/developers/addon/videomark/versions
警告・通知の一覧
```
Manifest V3 compatibility warning
警告: Firefox is adding support for manifest version 3 (MV3) extensions in Firefox 109.0, however, older versions of Firefox are only compatible with manifest version 2 (MV2) extensions. We recommend uploading Manifest V3 extensions as self-hosted for now to not break compatibility for your users.
For more information about the MV3 extension roll-out or self-hosting MV3 extensions, visit https://mzl.la/3hIwQXX
Manifest key not supported by the specified minimum Firefox version
警告: "strict_min_version" requires Firefox 78, which was released before version 109 introduced support for "action".
manifest.json …
```
=> build(firefox): MV3対応のFirefox v109を最小バージョンとして指定

playwright.config.js, public/manifest-firefox.json, src/lib/background/background.js, src/lib/pages/onboarding/onboarding-tour.svelte, src/lib/pages/popup/popup-history.svelte, src/lib/services/navigation.js, src/lib/services/storage.js
Fix https://github.com/webdino/sodium/issues/957
- Firefox のみ Manifest V2 に戻して、計測が自動的に始まらない問題を回避します。
- 一部 V2 と V3 で互換性がないので、共存可能なようにコードを変更します。
- デスクトップ版 Firefox が自動テスト対象になっていなかったので有効化しました。
=> Firefox の Manifest V3 対応をバックアウト

public/manifest-firefox.json
Fix https://github.com/webdino/sodium/issues/960
#240 で `manifest-firefox.json` のみ更新されていなかったため、そのフォローアップです。
=> Lemino 対応を Firefox 向けマニフェストに追加

src/lib/pages/routes/settings.svelte, src/lib/pages/settings/setting-item.svelte, src/lib/services/sessions.js, tests/pages.spec.js
Fix https://github.com/webdino/sodium/issues/969
この修正で、最初に UI (オンボーディングツアー) が読み込まれた時点でセッションが作成されて、ID が空になったりタイプが `personal` に変わったりすることはなくなります。本来は利用規約同意後に作成されるのが望ましいのかもしれませんが、センシティブな情報が含まれているわけでもないですし、後日全体リファクタリング時に見直したいと思います。今は #251 が優先なので、最低限の修正です。
=> 計測 ID が空になる場合がある問題を修正

.github/workflows/tests.yml, package.json, pnpm-lock.yaml, src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/Config.spec.js, src/lib/services/video-platforms.js, vite.config.js
Fix https://github.com/webdino/sodium/issues/981
原因は、ホスト名のワイルドカードを正規表現に変換する部分にバグがあり (バックスラッシュ欠落)、`get_video_platform()` でプラットフォームが取得できず `undefined` になっていたため、そもそも指定された挿入先の ID が使われていませんでした。
同じ原因で履歴ページ内の検索フィルターも動いていなかったことが判明 😓 またニコニコ動画のホスト名正規表現にもミスがありました。(#236 で変更された部分からコピペされたはずなのですが)
この正規表現が使われているのは UI だけで、計測には影響していないはずです。
問題を修正し Vitest で自動テストを走らせるようにしました。
=> YouTube で統計オーバーレイが隠れる場合がある問題を修正

src/lib/content/sodium/modules/SessionData.js
Fix https://github.com/webdino/sodium/issues/965
今日のミーティング中に話しましたが、(動画 →) チャンネルトップ → 動画 のページ遷移で必ず発生するようで、チャンネルトップの動画が非表示のまま DOM 上に残り、それが毎秒のチェックに引っ掛かっていることが原因でした。単純に非表示の `video` 要素を無視することで回避します。
=> YouTube で毎秒 delete video / new video found メッセージが出る問題を修正

src/lib/pages/history/history-item.svelte, src/lib/pages/history/quality-bar.svelte
Fix https://github.com/webdino/sodium/issues/987
小数第 2 位まで必ず表示されるようにします。
=> 視聴履歴で QoE 値の小数点以下が切り捨てられている問題を修正

cspell.config.yaml, src/lib/content/sodium/modules/TVerTypeHandler.js
Fix https://github.com/webdino/sodium/issues/812
動画のサムネイルとタイトルが正しく記録されるようにします。
また、関連動画を開いたときに計測が始まらない問題を解消します。(実はどの部分で修正されたのか分かっていませんが)
=> TVer 視聴履歴の問題を修正

src/lib/components/stats/stats-row.svelte, src/lib/content/sodium/modules/YouTubeTypeHandler.js, src/lib/services/history.js, src/lib/services/stats.js
Fix https://github.com/webdino/sodium/issues/1035
- `content-length` ヘッダーと `itag` クエリパラメーターが削除されているので、それぞれ別の方法で取得
- オーバーレイのスループット行が常時表示されない問題を修正
- 計測結果のスループットが表示されない問題を修正 (平均値として表示)
- 表示単位を kbps から Mbps へ変更
=> YouTube でスループットが取得できていない問題を修正

public/manifest.json
Fix https://github.com/webdino/sodium/issues/1053
YouTube に限らず `iframe` を使った埋め込み動画の計測に対応しているサービスはないはずなので、[`content_scripts`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts) の `all_frames` オプションを無効化して計測対象から除外します。
=> YouTube 埋め込み動画で VideoMark が作動してしまっている問題を修正

src/lib/content/sodium/modules/AbemaTVLiveTypeHandler.js, src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/VideoHandler.js
Fix https://github.com/webdino/sodium/issues/955
Fix https://github.com/webdino/sodium/issues/1051
- CM 判定が難しいため `is_cm()` は常に `false` を返すように
- 現状 `<video>` 要素はひとつしかないのでコードを簡素化
- 内部エラー「ignore this video」を修正
- サムネイルが取得できていない問題を修正
- 動画へのマウスホバーで計測オーバーレイを表示するよう CSS を修正
=> ABEMA 生放送の計測失敗を修正

src/lib/background/background.js, src/lib/services/runtime.js
Fix https://github.com/webdino/sodium/issues/1055
Firefox では引き続き Manifest v3 の実装が進められていますが、その過程で非互換が生じてしまっているようです。2 つ問題を確認したので取り急ぎ修正します。手元では Developer Edition (v128) を使っています。
1. `chrome.runtime.getContexts()` が実装されたものの `undefined` を返している ([実装このあたり](https://bugzilla.mozilla.org/show_bug.cgi?id=1875480))
2. `chrome.webRequest.onHeadersReceived.addListener()` で渡されるオブジェクトから `initiator` が消えている (いつからかは未調査)
=> Firefox で拡張機能のドロップダウンが表示されない問題を修正

src/lib/content/sodium/modules/TVerTypeHandler.js
一部のと言ってもパリ五輪の動画でしか確認できていませんが、通常の動画と異なり `og:image` が設定されていて、別オリジン (`https://olympic-assets.tver.jp`) に画像が配置されているので、そこから取得するようにします。
=> TVer で一部動画のサムネイルが表示されない問題を修正

src/lib/components/stats/stats-body.svelte, vite-plugin-package-extension.js
Fix https://github.com/webdino/sodium/issues/1084
Work around https://github.com/sveltejs/svelte/issues/10826
Svelte が `innerHTML` を出力しないようにコードを微調整します。他に `innerHTML` が使われているところは今のところ見当たりませんが、今後同じ問題が起きないようにビルド時のチェックも追加します。
=> YouTube で計測オーバーレイが展開されない問題を修正

src/lib/content/sodium/modules/Config.js
Fix #298
生放送のページでは、マウスホバーによって上部の黒いヘッダーと左側のナビゲーションの表示・非表示が切り替わるようになっていて、表示中だとウィンドウサイズによってはオーバーレイが隠れてしまうことがあります。オーバーレイの挿入ターゲットを変えることで問題を回避します。VOD には影響ありません。
=> ABEMA でオーバーレイ表示が一部隠れる問題を修正

src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/LeminoTypeHandler.js
Fix #306
Fix #308 
- オーバーレイが動画左上に表示されるタイトルと被るので右上に移動
- オーバーレイを動画マウスホバー時に表示するよう変更
- 広告と本編動画の判定基準を現行サイトに合わせて修正
- タイトルとサムネイルの取得方法も併せて変更 (サムネイルは通常の `og:image` で取得可能)
=> Lemino の計測問題を修正

src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/FodTypeHandler.js
Fix #305
Fix #309
- オーバーレイが動画左上に表示されるタイトルと被るので右上に移動
- オーバーレイを動画マウスホバー時のみ表示するよう変更
- 広告と本編動画の判定基準を現行サイトに合わせて修正
- タイトルとサムネイルの取得方法も併せて変更
=> FOD の計測問題を修正

src/lib/components/stats/stats-expander.svelte
Fix #312
`pointerdown` では `event.stopPropagation()` が効かないようなので、`click` イベントに差し替えて、動画自体がクリックされないようにします。
=> ニコニコでオーバーレイを開くと動画が止まる問題を修正

src/lib/background/background.js, src/lib/locales/en.js, src/lib/locales/ja.js, src/lib/pages/history/detail-panel.svelte, src/lib/pages/history/history-item.svelte, src/lib/pages/routes/history.svelte, src/lib/services/api.js, src/lib/services/history/index.js, src/lib/services/stats.js, src/lib/services/video-platforms.js, src/lib/typedefs.js
Fix #314
検索結果の一覧と詳細パネルでは、確定 QoE 値の計算が終わっていない場合、暫定 QoE 値が取得できていればその数値を表示していますが、計算が完了しているように見えてしまうので、表記を変更します。
アイコンを砂時計に変更
表示している数字が暫定値で、確定値は計算中であることを明記
- 確定 QoE 値を取得できているのに検索結果の UI も内部データベースも更新されていない問題を修正 (レコードキーの参照が number ではなく string で行われていたため)
- 1 時間以上確定 QoE 値が得られなかった場合はタイムアウトとし、エラーとして保存する
- ニコニコや FOD など QoE 計算に対応していないプラットフォームで QoE 値が永遠に計算中と表示される問題を修正 (非対応プラットフォームでは非対応と表示)
=> 検索結果の QoE 値表示に関する一連のバグを修正

src/lib/pages/history/detail-panel.svelte, src/lib/pages/history/history-item.svelte, src/lib/pages/history/video-thumbnail.svelte
Fix #317
サムネイルが取得できなかった、削除された、あるいはオフライン時に表示できない場合、現状壊れた画像が表示されてしまっているので、VideoMark のロゴをフォールバックとして表示します。
=> 動画サムネイルのフォールバックを設定

package.json, pnpm-lock.yaml, src/lib/services/history/index.js
Fix #320
Fix #322
検索結果に出てくる個々の履歴は、当初は必要最低限の情報だけ読み出しておいて、ページ上のビューポートに入ってから [`completeViewingHistoryItem()`](https://github.com/videomark/videomark/blob/99166adc89bc01e5ed75b30f384e42d97d0e03f7/src/lib/services/history/index.js#L111) で情報を追加するというパフォーマンス処理を行っていますが、これが意図せぬ検索条件のリセットにつながっていました。条件判定を加えてこの問題を回避します。
=> 検索条件の意図せぬリセットを防止

src/lib/content/sodium/modules/Config.js
Fix #328
オンデマンドの動画を再生中にスクロールダウンすると、動画が画面右下のミニプレーヤーへ移動しますが、領域が狭すぎてオーバーレイを表示しきれません。このため非表示にしてしまいます。
=> ABEMA のミニプレーヤーではオーバーレイを非表示に

src/lib/content/sodium/modules/AbemaTVVideoTypeHandler.js, src/lib/content/sodium/modules/VideoHandler.js
Fix #327
`https://abema.tv/channels/` 以下の動画が計測対象となっていないので、対象に追加します。プレーヤーは通常の動画と同じ。`AdObserver` 向けの CSS クエリも両対応としました。
=> ABEMA チャンネルに対応

src/lib/content/sodium/modules/NetflixTypeHandler.js
Fix #326
Netflix の内部 API (`getEpisodeThumbnail`) が例外を吐いているのが原因と分かったので、サムネイルの取得方法を変更しました。それから、インデックスページの予告編でも計測セッションが始まっていたので、他のサービスと同様にそれを回避するための `is_main_video` の判別を入れました。(`this.elm = elm` は `super` で呼び出されるため冗長なので削除)
=> Netflix で映画の計測が始まらない問題を修正

src/lib/content/sodium/modules/AbemaTVVideoTypeHandler.js
Fix https://github.com/videomark/videomark/issues/338
広告判定コードを変更して [見逃し視聴](https://help.abema.tv/hc/ja/articles/360013513952) にも対応可能にします。
=> ABEMA で見逃し視聴の広告が計測されている問題を修正

src/lib/content/sodium/modules/Config.js
Fix https://github.com/videomark/videomark/issues/336
タイトルと被らないように表示位置を変更しました。
=> Lemino の計測オーバーレイ位置を変更

cspell.config.yaml, src/lib/content/sodium/modules/TVerTypeHandler.js, src/lib/content/sodium/modules/VideoHandler.js
Fix #325
プレーヤーが Video.js から Streaks に変わったので、全面的にコードを書き直しました。オンデマンド、ライブ配信いずれにも対応しています。
=> TVer で計測ができていない問題を修正

.github/workflows/tests.yml, playwright.config.js, tests/common.js
Fix https://github.com/videomark/videomark/issues/316
Playwright v1.49 でヘッドレスの Chromium が更新されたのが原因でした。テストを新しいものに合わせます。
- https://github.com/microsoft/playwright/issues/33566
YouTube での暫定 QoE テストはタイムアウトで相変わらず失敗します。拡張機能ページ内のテストもランダムで失敗することがあり、原因はまだ確認できていませんが、少なくとも全部失敗することはなくなります。
=> Playwright テストがすべて失敗している問題を修正

package.json, src/lib/content/sodium/modules/Config.js
Config.get_settings() が意図しない値が得られている問題を修正しました。
この変更によってプロダクションビルドで設定が反映され動画視聴中のオーバーレイ部分の設定が適切に反映されるようになります。
(YouTubeで表示されない問題は別の原因)
=> コード分割によって設定が読み込まれない script URL の問題を修正

public/manifest.json, src/lib/content/content.js
Fix https://github.com/webdino/sodium/issues/1182
- `Object.defineProperty` で `fetch` の書き換えが禁止されているので、これを実行しているスクリプトの挿入を検知して、実行前に削除してしまいます。
- `content.js` がページ内スクリプトより前に実行されるよう、タイミングを `document_start` に変更します。そうすると `<body>` が存在しないので、`sodium.js` の挿入先を `document.documentElement` に変更します。
=> YouTube で QoE 計測とオーバーレイ表示が機能していない問題を修正

src/lib/services/navigation.js
Fix https://github.com/webdino/sodium/issues/1186
リアルタイム更新を実装するまでは「統計データを表示」ボタン押下時にタブを再読み込みするようにします。これで必ず再生中の動画が履歴ページに追加されて、統計データが表示されるようになります。
=> ポップアップから確実に統計データを開けるようにする

playwright.config.js, src/lib/content/sodium/modules/YouTubeTypeHandler.js, tests/overlay.spec.js
See https://github.com/webdino/sodium/issues/1182
YouTube の埋め込み動画で QoE 計測が実行されるよう、取り急ぎ改変しました。埋め込み URL を直接開いた場合には動きますが、iframe 内での再生は別途対応します。
ざっくりコードを削っているのは、`adaptiveFormats` が
```js
document.querySelector('#movie_player').getPlayerResponse().streamingData.adaptiveFormats
```
で直接取得でき、これなら通常ページにも埋め込みページにも存在していて常に最新のはずだからです。
=> YouTube の埋め込み動画 URL に対応

src/lib/components/stats/stats-body.svelte, src/lib/content/sodium/modules/Config.js, src/lib/content/sodium/modules/YouTubeTypeHandler.js
Fix https://github.com/webdino/sodium/issues/507
動画プレイヤーのクエリセレクターを変更して、ホーム画面上の動画も計測対象とします。その他若干リファクタリンクも入れました。
=> YouTube チャンネルホームでの計測に対応

src/lib/background/background.js, src/lib/content/sodium/modules/YouTubeTypeHandler.js
Fix https://github.com/webdino/sodium/issues/1216
#360 からのリグレッションを修正します 😢 
- CSP を削除する `declarativeNetRequest` API がうまく機能せず、既存のルールが無視されているようなので、毎回削除し新たに追加し直すようにしました。正規表現が間違っているのかと疑ったのですが、新規 Chrome プロフィールでは問題ないので、単に API の問題のようです。
- YouTube 動画チャンク URL パスの判定が間違っていました。
ちなみにオーバーレイ上のスループットも表示されていませんが、これは元々ちゃんと表示されていなかったように記憶しているし計測には支障ないので、後回しにします。(どういうチャート表示が正しいのか分かりません 🙃)
=> YouTube でスループットを取得できていない問題を修正
